### ISSUE TITLE
example is broken

### ISSUE THREAD

**Issue by stephenmathieson** [koajs/csrf#18]
```
~/dev/src/github.com/koajs/csrf on master ∴ node example
/Users/stephenmathieson/dev/src/github.com/koajs/csrf/node_modules/koa-session/index.js:45
    throw new TypeError('app instance required: `session(opts, app)`');
    ^

TypeError: app instance required: `session(opts, app)`
    at module.exports (/Users/stephenmathieson/dev/src/github.com/koajs/csrf/node_modules/koa-session/index.js:45:11)
    at Object.<anonymous> (/Users/stephenmathieson/dev/src/github.com/koajs/csrf/example.js:7:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by jonathanong** [comment]
ah shoot. https://github.com/koajs/session need to update `koa-session`'s API usage
